export const TYPING_PHRASES = [
  'FRONTEND ENGINEER',
  'FULLSTACK ENGINEER',
  'WEB3 EXPERT',
  'BLOCKCHAIN ENTHUSIAST',
] as const;

export const LOADING_STAGES = [
  'INITIALIZING...',
  'LOADING ASSETS...',
  'CONNECTING TO SERVER...',
  'PARSING DATA...',
  'RENDERING UI...',
  'PORTFOLIO READY!',
] as const;